# https://taskfile.dev/
version: "3"

dotenv: ["dev.env"]

vars:
  PROJECT_NAME: Sample
  PYTHON_VERSION: 3.8
  VENV: sample_api
  PYTHON: python3
  ENV: local

tasks:
  venv-create:
    status:
      - "test -f {{.VENV}}/bin/activate"
    cmds:
      - "python3 -m venv {{.VENV}}"
      - ". {{.VENV}}/bin/activate"
      - "python3 -m pip install --upgrade pip"
      - "pip install poetry"
      - "poetry install"
    preconditions:
      - sh: "which poetry"
        msg: "No poetry found"
      - sh: "which {{.PYTHON}}"
        msg: "No {{.PYTHON}} found"

  venv-activate:
    deps:
      - venv:create
    cmds:
      - ". {{.VENV}}/bin/activate"

  pyenv-create:
    cmds:
      - "pyenv virtualenv {{.PYTHON_VERSION}} {{.VENV}}"

  pyenv-setup:
    cmds:
      - "python3 -m pip install --upgrade pip"
      - "pip install poetry"
      - "poetry install"

  pyenv-activate:
    cmds:
      - "pyenv activate {{.VENV}}"

  pyenv-remove:
    cmds:
      - "pyenv virtualenv-delete {{.VENV}}"

  docker-build:
    desc: "Build docker containers for the configured environment  type (test, prod, local)"
    cmds:
      - "docker compose -p {{.PROJECT_NAME}} -f ./configs/docker/docker-compose-{{.ENV}}.yml build {{.CLI_ARGS}}"

  docker-up:
    desc: "Start full app in docker"
    cmds:
      - "docker compose -p {{.PROJECT_NAME}} -f ./configs/docker/docker-compose-{{.ENV}}.yml up -d"

  docker-db-up:
    desc: "Start DB containers only"
    cmds:
      - "docker compose -p {{.PROJECT_NAME}} -f ./configs/docker/docker-compose-{{.ENV}}.yml up -d db"

  docker-db-backup:
    desc: "Create a backup file of the current data in the DB"
    cmds:
      - "scripts/db_backup.sh"

  docker-stop:
    desc: "Stop all containers"
    cmds:
      - "docker compose -p {{.PROJECT_NAME}} -f ./configs/docker/docker-compose-{{.ENV}}.yml stop"

  docker-down:
    desc: "Down all containers"
    cmds:
      - "docker compose -p {{.PROJECT_NAME}} -f ./configs/docker/docker-compose-{{.ENV}}.yml down --remove-orphans"

  docker-restart:
    desc: "Restart all containers"
    cmds:
      - "docker compose -p {{.PROJECT_NAME}} -f ./configs/docker/docker-compose-{{.ENV}}.yml restart"

  docker-clean-logs:
    desc: "Clear logs of a specific Docker container by name or ID. ex: task docker-clean-logs -- <container-name>"
    cmds:
      - ./scripts/bash_task/clean-docker-logs.sh {{.CLI_ARGS}}

  isort-format:
    cmds:
      - "poetry run isort ."

  isort-check:
    cmds:
      - "poetry run isort --check --diff ."

  black-format:
    cmds:
      - "poetry run black ."

  black-check:
    cmds:
      - "poetry run black --check ."

  mypy:
    cmds:
      - "poetry run mypy ."

  pylint:
    cmds:
      - "poetry run pylint app"

  pytest-docker:
    desc: "run pytest in docker (pass args after '--')"
    cmds:
      - "docker-compose run app ./docker-entrypoint.sh pytest {{.CLI_ARGS}}"

  pytest:
    desc: "run pytest locally (pass args after '--')"
    deps:
      - docker-db-up
    cmds:
      - alembic downgrade base
      - alembic upgrade head
      - poetry run pytest -s -vv -x tests/ --cov=app {{.CLI_ARGS}}

  migration:
    desc: "create alembic migration (pass args after '--')"
    cmds:
      - "alembic revision --autogenerate {{.CLI_ARGS}}"

  upgrade:
    desc: "apply all alembic migration"
    cmds:
    - "alembic upgrade head"

  downgrade:
    desc: "rollback all alembic migrations"
    cmds:
    - "alembic downgrade base"

  run:
    desc: "Run app locally"
    deps:
      - docker-db-up
    cmds:
      - ./docker-entrypoint.sh api

  # groups
  format:
    desc: "run code formatters"
    cmds:
      - task: isort-format
      - task: black-format

  lint:
    desc: "run linters"
    cmds:
      - task: isort-check
      - task: black-check
      - task: pylint
      - task: mypy
