openapi: 3.0.3
info:
  title: Pronotez Backend API
  description: A description of my API
  version: 0.0.1
servers:
  - url: http://localhost:8000/api
paths:
  /clients:
    get:
      summary: Gets simplified client list
      description: Gets simplified client list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/client_list'
        '404':
          description: Not Found
  /clients/save:
    put:
      summary: Create or update new client
      description: Create or update new client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/client_profile'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/client_profile'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /clients/{id}:
    get:
      summary: Get a single client profile
      description: Get a single client profile
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/client_profile'
        '404':
          description: Not Found
  /notes/save:
    put:
      summary: Saves a new note or updates an existing note
      description: Saves a new note or updates an existing note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note_info:
                  $ref: '#/components/schemas/note_info'
                note_text:
                  $ref: '#/components/schemas/note_text'
              required:
                - note_info
                - note_text
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /notes/generate:
    put:
      summary: Generate a new note
      description: Generate a new note
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/note_info'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/note_text'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
components:
  schemas:
    client_record:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 6d8b3641-2916-4395-b5bf-65e8ba1dc406
        firsName:
          type: string
          example: Alice
        lastName:
          type: string
          example: In chains
      required:
        - id
        - name
    client_list:
      type: array
      items:
        $ref: '#/components/schemas/client_record'
    client_profile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 6d8b3641-2916-4395-b5bf-65e8ba1dc406
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        dob:
          type: string
          format: date
          example: 1990-01-01
        address:
          type: string
          example: 123 Main St
        citizenship:
          type: boolean
          example: true
        insurance:
          type: string
          example: ACME Insurance
        presentingProblem:
          type: string
          example: Headache
        medicalConditions:
          type: string
          example: Diabetes
        medications:
          type: string
          example: Insulin
        pcpName:
          type: string
          example: Dr. Smith
        pcpPhone:
          type: string
          example: 555-1234
        pcpAddress:
          type: string
          example: 456 Elm St
        mentalConditions:
          type: string
          example: Anxiety
        psychiatricMedications:
          type: string
          example: Xanax
        psychiatristName:
          type: string
          example: Dr. Jones
        psychiatristPhone:
          type: string
          example: 555-5678
    note_info:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 6d8b3641-2916-4395-b5bf-65e8ba1dc406
        client_id:
          type: string
          format: uuid
          example: 02d0e036-23d9-4ab3-af3b-1f01850e0580
        note_date:
          type: string
          format: date
          example: 2023-04-09
        sessions:
          type: array
          items:
            $ref: '#/components/schemas/session'
      required:
        - id
        - client_id
        - note_date
        - sessions
    session:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 8a4d4d3f-2075-4c17-88e5-5d5a75a136a5
        position:
          type: integer
          example: 1
        service:
          type: string
          example: Therapy
        details:
          type: string
          example: The client is doing well in therapy.
      required:
        - id
        - position
        - service
        - details
    note_text:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 3c60b874-d203-421c-a5a5-8dc41c2d38a5
        service_need:
          type: string
          example: The client needs help with managing their anxiety.
        intervention:
          type: string
          example: The therapist provided psychoeducation on anxiety management techniques.
        outcome:
          type: string
          example: The client reported feeling more confident in managing their anxiety after the session.
        follow_up:
          type: string
          example: The therapist scheduled a follow-up session in two weeks to check in on the client's progress.
      required:
        - id
        - service_need
        - intervention
        - outcome
        - follow_up
